In [1]:
import csv
from pathlib import Path
import pandas as pd

In [2]:
menudf=pd.read_csv('menudata.csv')
salesdf=pd.read_csv('salesdata.csv')

In [3]:
menudf.head(5)

,item,category,description,price,cost
0,edamame,appetizers,"boiled soybeans, maldon sea salt",4.0,1
1,house salad,appetizers,"mixed greens, cherry tomatoes, cucumber, house...",4.0,2
2,cucumber sunomono salad,appetizers,"cucumber, ponzu dressing, pickled ginger sprou...",5.0,2
3,hiyashi wakame seaweed salad,appetizers,"sweet soy-marinated wakame seaweed threads, pi...",5.0,2
4,agedashi tofu,appetizers,"tempura battered tofu, katsuobushi, tsuyu brot...",5.0,2

In [4]:
salesdf.head(5)

,Line_Item_ID,Date,Credit_Card_Number,Quantity,Menu_Item
0,1,01-01-2017,7437926611570799,1,spicy miso ramen
1,2,01-01-2017,7437926611570799,1,spicy miso ramen
2,3,01-01-2017,8421920068932819,3,tori paitan ramen
3,4,01-01-2017,8421920068932819,3,tori paitan ramen
4,5,01-01-2017,4787310681569648,1,truffle butter ramen

In [5]:
salesdf = salesdf.rename({'Menu_Item':'item'}, axis='columns')
salesdf.head(3)

   Line_Item_ID        Date  Credit_Card_Number  Quantity               item
0             1  01-01-2017    7437926611570799         1   spicy miso ramen
1             2  01-01-2017    7437926611570799         1   spicy miso ramen
2             3  01-01-2017    8421920068932819         3  tori paitan ramen

In [6]:
salesgroup = salesdf.groupby(['item']).sum()
salesgroup
# menudf

,Line_Item_ID,Credit_Card_Number,Quantity
item,,,
burnt garlic tonkotsu ramen,252065727.0,3.376617e+19,9070.0
miso crab ramen,245834699.0,3.256509e+19,8890.0
nagomi shoyu,248863214.0,3.280075e+19,9132.0
shio ramen,251597212.0,3.324208e+19,9180.0
soft-shell miso crab ramen,250939165.0,3.331446e+19,9130.0
spicy miso ramen,248767867.0,3.498825e+19,9238.0
tonkotsu ramen,249868856.0,3.393332e+19,9288.0
tori paitan ramen,252738187.0,3.374608e+19,9156.0
truffle butter ramen,249741157.0,3.407522e+19,8982.0
vegetarian curry + king trumpet mushroom ramen,245741009.0,3.293250e+19,8824.0
vegetarian spicy miso,251063657.0,3.436609e+19,9216.0

In [7]:
# adding price and cost columns from menudf to salesgroup

for row in menudf.values:
    item=row[0]
    price = row[-2]
    cost = row[-1]
    for line in salesgroup.index:
        if item == line:
            salesgroup['price']=price
            salesgroup['cost']=cost
            
salesgroup

,Line_Item_ID,Credit_Card_Number,Quantity,price,cost
item,,,,,
burnt garlic tonkotsu ramen,252065727.0,3.376617e+19,9070.0,14.0,7
miso crab ramen,245834699.0,3.256509e+19,8890.0,14.0,7
nagomi shoyu,248863214.0,3.280075e+19,9132.0,14.0,7
shio ramen,251597212.0,3.324208e+19,9180.0,14.0,7
soft-shell miso crab ramen,250939165.0,3.331446e+19,9130.0,14.0,7
spicy miso ramen,248767867.0,3.498825e+19,9238.0,14.0,7
tonkotsu ramen,249868856.0,3.393332e+19,9288.0,14.0,7
tori paitan ramen,252738187.0,3.374608e+19,9156.0,14.0,7
truffle butter ramen,249741157.0,3.407522e+19,8982.0,14.0,7
vegetarian curry + king trumpet mushroom ramen,245741009.0,3.293250e+19,8824.0,14.0,7
vegetarian spicy miso,251063657.0,3.436609e+19,9216.0,14.0,7

In [8]:
# adding revenue, cogs, and profit columns to salesgroup

salesgroup['revenue']=salesgroup['Quantity']*salesgroup['price']

salesgroup['cogs']=salesgroup['Quantity']*salesgroup['cost']

salesgroup['profit']=salesgroup['revenue']*salesgroup['cogs']

salesgroup

,Line_Item_ID,Credit_Card_Number,Quantity,price,cost,revenue,cogs,profit
item,,,,,,,,
burnt garlic tonkotsu ramen,252065727.0,3.376617e+19,9070.0,14.0,7,126980.0,63490.0,8.061960e+09
miso crab ramen,245834699.0,3.256509e+19,8890.0,14.0,7,124460.0,62230.0,7.745146e+09
nagomi shoyu,248863214.0,3.280075e+19,9132.0,14.0,7,127848.0,63924.0,8.172556e+09
shio ramen,251597212.0,3.324208e+19,9180.0,14.0,7,128520.0,64260.0,8.258695e+09
soft-shell miso crab ramen,250939165.0,3.331446e+19,9130.0,14.0,7,127820.0,63910.0,8.168976e+09
spicy miso ramen,248767867.0,3.498825e+19,9238.0,14.0,7,129332.0,64666.0,8.363383e+09
tonkotsu ramen,249868856.0,3.393332e+19,9288.0,14.0,7,130032.0,65016.0,8.454161e+09
tori paitan ramen,252738187.0,3.374608e+19,9156.0,14.0,7,128184.0,64092.0,8.215569e+09
truffle butter ramen,249741157.0,3.407522e+19,8982.0,14.0,7,125748.0,62874.0,7.906280e+09
vegetarian curry + king trumpet mushroom ramen,245741009.0,3.293250e+19,8824.0,14.0,7,123536.0,61768.0,7.630572e+09
vegetarian spicy miso,251063657.0,3.436609e+19,9216.0,14.0,7,129024.0,64512.0,8.323596e+09

In [35]:
# @TODO: Initialize dict object to hold our key-value pairs of items and metrics
finalreport= {}
salesgroup['item']=salesgroup.index
salesgroup

,Line_Item_ID,Credit_Card_Number,Quantity,price,cost,revenue,cogs,profit,item
item,,,,,,,,,
burnt garlic tonkotsu ramen,252065727.0,3.376617e+19,9070.0,14.0,7,126980.0,63490.0,8.061960e+09,burnt garlic tonkotsu ramen
miso crab ramen,245834699.0,3.256509e+19,8890.0,14.0,7,124460.0,62230.0,7.745146e+09,miso crab ramen
nagomi shoyu,248863214.0,3.280075e+19,9132.0,14.0,7,127848.0,63924.0,8.172556e+09,nagomi shoyu
shio ramen,251597212.0,3.324208e+19,9180.0,14.0,7,128520.0,64260.0,8.258695e+09,shio ramen
soft-shell miso crab ramen,250939165.0,3.331446e+19,9130.0,14.0,7,127820.0,63910.0,8.168976e+09,soft-shell miso crab ramen
spicy miso ramen,248767867.0,3.498825e+19,9238.0,14.0,7,129332.0,64666.0,8.363383e+09,spicy miso ramen
tonkotsu ramen,249868856.0,3.393332e+19,9288.0,14.0,7,130032.0,65016.0,8.454161e+09,tonkotsu ramen
tori paitan ramen,252738187.0,3.374608e+19,9156.0,14.0,7,128184.0,64092.0,8.215569e+09,tori paitan ramen
truffle butter ramen,249741157.0,3.407522e+19,8982.0,14.0,7,125748.0,62874.0,7.906280e+09,truffle butter ramen
vegetarian curry + king trumpet mushroom ramen,245741009.0,3.293250e+19,8824.0,14.0,7,123536.0,61768.0,7.630572e+09,vegetarian curry + king trumpet mushroom ramen
vegetarian spicy miso,251063657.0,3.436609e+19,9216.0,14.0,7,129024.0,64512.0,8.323596e+09,vegetarian spicy miso

In [42]:
# adding metrics to dictionary


for row in salesgroup.values:
        
    count = row[2]
    revenue = row[-4]
    cogs = row[-3]
    profit=row[-2]
    item = row[-1]

    finalreport[item]={(f"01-count:{count}, 02-revenue:{revenue}, 03-cogs:{cogs}, 04-profit:{profit}")}
    
finalreport
for item,val in finalreport.items():
    print(item,val)

burnt garlic tonkotsu ramen {'01-count:9070.0, 02-revenue:126980.0, 03-cogs:63490.0, 04-profit:8061960200.0'}
miso crab ramen {'01-count:8890.0, 02-revenue:124460.0, 03-cogs:62230.0, 04-profit:7745145800.0'}
nagomi shoyu {'01-count:9132.0, 02-revenue:127848.0, 03-cogs:63924.0, 04-profit:8172555552.0'}
shio ramen {'01-count:9180.0, 02-revenue:128520.0, 03-cogs:64260.0, 04-profit:8258695200.0'}
soft-shell miso crab ramen {'01-count:9130.0, 02-revenue:127820.0, 03-cogs:63910.0, 04-profit:8168976200.0'}
spicy miso ramen {'01-count:9238.0, 02-revenue:129332.0, 03-cogs:64666.0, 04-profit:8363383112.0'}
tonkotsu ramen {'01-count:9288.0, 02-revenue:130032.0, 03-cogs:65016.0, 04-profit:8454160512.0'}
tori paitan ramen {'01-count:9156.0, 02-revenue:128184.0, 03-cogs:64092.0, 04-profit:8215568928.0'}
truffle butter ramen {'01-count:8982.0, 02-revenue:125748.0, 03-cogs:62874.0, 04-profit:7906279752.0'}
vegetarian curry + king trumpet mushroom ramen {'01-count:8824.0, 02-revenue:123536.0, 03-cogs:61768.0, 04-profit:7630571648.0'}
vegetarian spicy miso {'01-count:9216.0, 02-revenue:129024.0, 03-cogs:64512.0, 04-profit:8323596288.0'}

In [39]:
with open ('PyRamen_Report2.txt','w') as file:
    
    file.write(f"{key,val}\n") for key,val in

In [ ]:
with open('dog.txt', 'w') as my_file:
    [ my_file.write(f'{st}\n') for st in list_of_strings ]